{
  "model": {
    "mlp_layers": [512, 512, 256]
  },
  "training": {
    "max_hours": 24,
    "seed": 42,
    "num_episodes": 200000,
    "evaluate_every": 200,
    "reward_beta": 0.5,
    "opponent_update_every": 1000,
    "game_enable_blind_nil": false
  },
  "dqn": {
    "save_path": "experiments/spades_selfplay_dqn_0.5_12h"
  },
  "agent": {
    "replay_memory_size": 200000,
    "replay_memory_init_size": 2000,
    "batch_size": 256,
    "save_every": 5000
  },
  "nfsp": {
    "save_path": "experiments/spades_selfplay_nfsp_0.5_12h",
    "hidden_layers_sizes": [512, 512, 256],
    "q_mlp_layers": [512, 512, 256],
    "reservoir_buffer_capacity": 20000,
    "anticipatory_param": 0.1,
    "batch_size": 256,
    "train_every": 1,
    "rl_learning_rate": 0.00005,
    "sl_learning_rate": 0.005,
    "min_buffer_size_to_learn": 100,
    "q_replay_memory_size": 200000,
    "q_replay_memory_init_size": 2000,
    "q_update_target_estimator_every": 1000,
    "q_discount_factor": 0.99,
    "q_epsilon_start": 1.0,
    "q_epsilon_end": 0.1,
    "q_epsilon_decay_steps": 20000,
    "q_batch_size": 256,
    "q_train_every": 1,
    "evaluate_with": "average_policy",
    "save_every": 5000
  },
  "dmc": {
    "xpid": "spades_dmc",
    "save_dir": "experiments/spades_dmc_0.5_12h",
    "load_model": false,
    "cuda": "auto",
    "save_interval": 30,
    "num_actor_devices": 1,
    "num_actors": 5,
    "training_device": "0",
    "total_frames": 5000000,
    "exp_epsilon": 0.01,
    "batch_size": 32,
    "unroll_length": 100,
    "num_buffers": 50,
    "num_threads": 4,
    "max_grad_norm": 40,
    "learning_rate": 0.0001,
    "alpha": 0.99,
    "momentum": 0,
    "epsilon": 0.00001
  },
  "cfr": {
    "seed": 42,
    "num_episodes": 5000,
    "num_eval_games": 200,
    "evaluate_every": 100,
    "max_nodes_per_iter": 200000,
    "max_seconds_per_iter": 10,
    "log_dir": "experiments/spades_cfr_result_0.5_12h"
  },
  "drqn": {
    "save_path": "experiments/spades_selfplay_drqn",
    "lstm_hidden_size": 256,
    "lstm_num_layers": 1,
    "seq_len": 16,
    "embed_dim": 256,
    "mlp_layers": [256],
    "max_episodes": 8000,
    "batch_size": "auto",
    "learning_rate": 0.00003,
    "cuda": "auto",
    "num_actors": "auto",
    "gpu_fraction": 0.8,
    "total_frames": 50000000,
    "exp_epsilon": 0.05,
    "sync_every": 100,
    "train_steps_per_sync": 16,
    "max_grad_norm": 40,
    "update_target_every": 1000,
    "discount_factor": 0.99,
    "save_interval": 30,
    "opponent_pool_size": 10,
    "opponent_update_every": 2000,
    "eval_every_frames": 500000,
    "epsilon_decay_games": 20000
  }
}
