is_pool:
  num_proposals: 3456
  num_proposals_limit: 3456
  min_pool_size: 100

budget:
  thresholds:
  - remaining_in: 20
    top_k: 64
    max_samples: 256
  - remaining_in: 28
    top_k: 32
    max_samples: 128
  - remaining_in: 32
    top_k: 16
    max_samples: 64
  - remaining_in: 34
    top_k: 8
    max_samples: 32
  default:
    top_k: 8
    max_samples: 32

bad_action_weight: "x"
bad_action_penalty_factor: 0.81
gamma: 1.0
trick_num_threshold: 8
swap_is_fill: true
multiplier_clip: 40.0
multiplier_clip_factor: 1.0
